spring:
  application:
    name: agilemvp
  datasource:
    url: jdbc:h2:file:./data/agilemvpdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO
    cop.kbds.agilemvp: DEBUG
